server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lostfound?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.lostfound.pojo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# 自定义配置
app:
  jwt:
    expiration: 86400000  # 24小时，单位毫秒
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8HhV334TpG2CCBqrZR
    access-key-secret: VETRyHVowHgNdg5sW6uHrknbKKhCOb
    bucket-name: java-479